// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlgorithmState string

const (
	AlgorithmStatePENDING         AlgorithmState = "PENDING"
	AlgorithmStatePROCESSING      AlgorithmState = "PROCESSING"
	AlgorithmStateSUCCEEDED       AlgorithmState = "SUCCEEDED"
	AlgorithmStateFAILEDHANDLED   AlgorithmState = "FAILED_HANDLED"
	AlgorithmStateFAILEDUNHANDLED AlgorithmState = "FAILED_UNHANDLED"
)

func (e *AlgorithmState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlgorithmState(s)
	case string:
		*e = AlgorithmState(s)
	default:
		return fmt.Errorf("unsupported scan type for AlgorithmState: %T", src)
	}
	return nil
}

type NullAlgorithmState struct {
	AlgorithmState AlgorithmState
	Valid          bool // Valid is true if AlgorithmState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlgorithmState) Scan(value interface{}) error {
	if value == nil {
		ns.AlgorithmState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlgorithmState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlgorithmState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlgorithmState), nil
}

type BackoffStrategy string

const (
	BackoffStrategyBACKOFFSTRATEGYLINEAR      BackoffStrategy = "BACKOFF_STRATEGY_LINEAR"
	BackoffStrategyBACKOFFSTRATEGYEXPONENTIAL BackoffStrategy = "BACKOFF_STRATEGY_EXPONENTIAL"
)

func (e *BackoffStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BackoffStrategy(s)
	case string:
		*e = BackoffStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for BackoffStrategy: %T", src)
	}
	return nil
}

type NullBackoffStrategy struct {
	BackoffStrategy BackoffStrategy
	Valid           bool // Valid is true if BackoffStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBackoffStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.BackoffStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BackoffStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBackoffStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BackoffStrategy), nil
}

type DatafunctionStorageType string

const (
	DatafunctionStorageTypeDATAFUNCTIONSTORAGEFILESYSTEM DatafunctionStorageType = "DATAFUNCTION_STORAGE_FILESYSTEM"
	DatafunctionStorageTypeDATAFUNCTIONSTORAGEGCS        DatafunctionStorageType = "DATAFUNCTION_STORAGE_GCS"
	DatafunctionStorageTypeDATAFUNCTIONSTORAGES3         DatafunctionStorageType = "DATAFUNCTION_STORAGE_S3"
)

func (e *DatafunctionStorageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DatafunctionStorageType(s)
	case string:
		*e = DatafunctionStorageType(s)
	default:
		return fmt.Errorf("unsupported scan type for DatafunctionStorageType: %T", src)
	}
	return nil
}

type NullDatafunctionStorageType struct {
	DatafunctionStorageType DatafunctionStorageType
	Valid                   bool // Valid is true if DatafunctionStorageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDatafunctionStorageType) Scan(value interface{}) error {
	if value == nil {
		ns.DatafunctionStorageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DatafunctionStorageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDatafunctionStorageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DatafunctionStorageType), nil
}

type ExecutionStatus string

const (
	ExecutionStatusEXECUTIONSTATUSUNSPECIFIED ExecutionStatus = "EXECUTION_STATUS_UNSPECIFIED"
	ExecutionStatusEXECUTIONSTATUSSUCCESSFUL  ExecutionStatus = "EXECUTION_STATUS_SUCCESSFUL"
	ExecutionStatusEXECUTIONSTATUSFAILED      ExecutionStatus = "EXECUTION_STATUS_FAILED"
)

func (e *ExecutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionStatus(s)
	case string:
		*e = ExecutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionStatus: %T", src)
	}
	return nil
}

type NullExecutionStatus struct {
	ExecutionStatus ExecutionStatus
	Valid           bool // Valid is true if ExecutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionStatus), nil
}

type FailureCategory string

const (
	FailureCategoryFAILURECATEGORYHANDLED      FailureCategory = "FAILURE_CATEGORY_HANDLED"
	FailureCategoryFAILURECATEGORYUNHANDLED    FailureCategory = "FAILURE_CATEGORY_UNHANDLED"
	FailureCategoryFAILURECATEGORYCOULDNTREACH FailureCategory = "FAILURE_CATEGORY_COULDNT_REACH"
)

func (e *FailureCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FailureCategory(s)
	case string:
		*e = FailureCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for FailureCategory: %T", src)
	}
	return nil
}

type NullFailureCategory struct {
	FailureCategory FailureCategory
	Valid           bool // Valid is true if FailureCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFailureCategory) Scan(value interface{}) error {
	if value == nil {
		ns.FailureCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FailureCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFailureCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FailureCategory), nil
}

type FailureSource string

const (
	FailureSourceFAILURESOURCEWORKER FailureSource = "FAILURE_SOURCE_WORKER"
	FailureSourceFAILURESOURCECORE   FailureSource = "FAILURE_SOURCE_CORE"
)

func (e *FailureSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FailureSource(s)
	case string:
		*e = FailureSource(s)
	default:
		return fmt.Errorf("unsupported scan type for FailureSource: %T", src)
	}
	return nil
}

type NullFailureSource struct {
	FailureSource FailureSource
	Valid         bool // Valid is true if FailureSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFailureSource) Scan(value interface{}) error {
	if value == nil {
		ns.FailureSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FailureSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFailureSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FailureSource), nil
}

type RegistrationStatus string

const (
	RegistrationStatusREGISTRATIONSTATUSUNSPECIFIED RegistrationStatus = "REGISTRATION_STATUS_UNSPECIFIED"
	RegistrationStatusREGISTRATIONSTATUSSUCCESSFUL  RegistrationStatus = "REGISTRATION_STATUS_SUCCESSFUL"
	RegistrationStatusREGISTRATIONSTATUSFAILED      RegistrationStatus = "REGISTRATION_STATUS_FAILED"
)

func (e *RegistrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegistrationStatus(s)
	case string:
		*e = RegistrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RegistrationStatus: %T", src)
	}
	return nil
}

type NullRegistrationStatus struct {
	RegistrationStatus RegistrationStatus
	Valid              bool // Valid is true if RegistrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegistrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RegistrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegistrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegistrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegistrationStatus), nil
}

type ResultType string

const (
	ResultTypeStruct ResultType = "struct"
	ResultTypeArray  ResultType = "array"
	ResultTypeValue  ResultType = "value"
	ResultTypeNone   ResultType = "none"
)

func (e *ResultType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResultType(s)
	case string:
		*e = ResultType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResultType: %T", src)
	}
	return nil
}

type NullResultType struct {
	ResultType ResultType
	Valid      bool // Valid is true if ResultType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResultType) Scan(value interface{}) error {
	if value == nil {
		ns.ResultType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResultType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResultType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResultType), nil
}

type TriggerSource string

const (
	TriggerSourceTRIGGERSOURCEUNSPECIFIED TriggerSource = "TRIGGER_SOURCE_UNSPECIFIED"
	TriggerSourceTRIGGERSOURCECRON        TriggerSource = "TRIGGER_SOURCE_CRON"
	TriggerSourceTRIGGERSOURCEWEBHOOK     TriggerSource = "TRIGGER_SOURCE_WEBHOOK"
	TriggerSourceTRIGGERSOURCEUI          TriggerSource = "TRIGGER_SOURCE_UI"
	TriggerSourceTRIGGERSOURCECLI         TriggerSource = "TRIGGER_SOURCE_CLI"
)

func (e *TriggerSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerSource(s)
	case string:
		*e = TriggerSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerSource: %T", src)
	}
	return nil
}

type NullTriggerSource struct {
	TriggerSource TriggerSource
	Valid         bool // Valid is true if TriggerSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerSource) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerSource), nil
}

type TriggerStatus string

const (
	TriggerStatusTRIGGERSTATUSUNSPECIFIED TriggerStatus = "TRIGGER_STATUS_UNSPECIFIED"
	TriggerStatusTRIGGERSTATUSNOTARGETS   TriggerStatus = "TRIGGER_STATUS_NO_TARGETS"
	TriggerStatusTRIGGERSTATUSPENDING     TriggerStatus = "TRIGGER_STATUS_PENDING"
	TriggerStatusTRIGGERSTATUSACCEPTED    TriggerStatus = "TRIGGER_STATUS_ACCEPTED"
	TriggerStatusTRIGGERSTATUSREJECTED    TriggerStatus = "TRIGGER_STATUS_REJECTED"
)

func (e *TriggerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerStatus(s)
	case string:
		*e = TriggerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerStatus: %T", src)
	}
	return nil
}

type NullTriggerStatus struct {
	TriggerStatus TriggerStatus
	Valid         bool // Valid is true if TriggerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerStatus), nil
}

type WindowState string

const (
	WindowStatePENDING            WindowState = "PENDING"
	WindowStateFAILED             WindowState = "FAILED"
	WindowStatePROCESSING         WindowState = "PROCESSING"
	WindowStatePROCESSINGFINISHED WindowState = "PROCESSING_FINISHED"
)

func (e *WindowState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WindowState(s)
	case string:
		*e = WindowState(s)
	default:
		return fmt.Errorf("unsupported scan type for WindowState: %T", src)
	}
	return nil
}

type NullWindowState struct {
	WindowState WindowState
	Valid       bool // Valid is true if WindowState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWindowState) Scan(value interface{}) error {
	if value == nil {
		ns.WindowState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WindowState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWindowState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WindowState), nil
}

type WorkflowSource string

const (
	WorkflowSourceWORKFLOWSOURCEWORKER    WorkflowSource = "WORKFLOW_SOURCE_WORKER"
	WorkflowSourceWORKFLOWSOURCEUNDEFINED WorkflowSource = "WORKFLOW_SOURCE_UNDEFINED"
)

func (e *WorkflowSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowSource(s)
	case string:
		*e = WorkflowSource(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowSource: %T", src)
	}
	return nil
}

type NullWorkflowSource struct {
	WorkflowSource WorkflowSource
	Valid          bool // Valid is true if WorkflowSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowSource) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowSource), nil
}

type Algorithm struct {
	ID                       int64
	Name                     string
	Version                  string
	ProcessorID              int64
	WindowTypeID             int64
	ResultType               ResultType
	Created                  pgtype.Timestamp
	Description              string
	SelfLookbackCount        int64
	SelfLookbackTimedelta    int64
	SelfLookbackGapCount     int64
	SelfLookbackGapTimedelta int64
}

type AlgorithmDependency struct {
	ID                   int64
	FromAlgorithmID      int64
	ToAlgorithmID        int64
	FromWindowTypeID     int64
	ToWindowTypeID       int64
	FromProcessorID      int64
	ToProcessorID        int64
	Created              pgtype.Timestamp
	LookbackCount        int64
	LookbackTimedelta    int64
	LookbackGapCount     int64
	LookbackGapTimedelta int64
}

type AlgorithmExecutionPath struct {
	FinalAlgoID                  int64
	NumDependencies              int32
	AlgoIDPath                   string
	WindowTypeIDPath             string
	ProcIDPath                   string
	LookbackCountPath            string
	LookbackTimedeltaPath        string
	SelfLookbackCountPath        string
	SelfLookbackTimedeltaPath    string
	LookbackGapCountPath         string
	LookbackGapTimedeltaPath     string
	SelfLookbackGapCountPath     string
	SelfLookbackGapTimedeltaPath string
}

// Plot annotations with time ranges and metadata
type Annotation struct {
	ID int64
	// Start time of the annotation time window
	TimeFrom pgtype.Timestamp
	// End time of the annotation time window
	TimeTo   pgtype.Timestamp
	Metadata []byte
	// Detailed description of the annotation
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
}

// Junction table linking annotations to algorithms
type AnnotationAlgorithm struct {
	AnnotationID int64
	AlgorithmID  int64
}

// Junction table linking annotations to window types
type AnnotationWindowType struct {
	AnnotationID int64
	WindowTypeID int64
}

type DataFunction struct {
	Name                    string
	AstHash                 string
	GitCommitHash           string
	WorkerName              string
	OutputModel             []byte
	IsActive                pgtype.Bool
	InputModel              []byte
	ExecutionTimeoutSeconds pgtype.Int4
	TtlSeconds              pgtype.Int4
	RegisteredAt            pgtype.Timestamptz
}

type DatafunctionExecution struct {
	ID            int32
	WorkflowRunID int32
	Uri           string
	Status        ExecutionStatus
	Completed     bool
	RequestedAt   pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
}

type DatafunctionStorageBackend struct {
	ID          int32
	BaseUri     string
	StorageType interface{}
}

type Metadata struct {
	WindowsID     int64
	WindowTypeID  int64
	MetadataKey   string
	MetadataValue pgtype.Float8
	MetadataArray []float64
	MetadataJson  []byte
}

type MetadataField struct {
	ID          int64
	Name        string
	Description string
	Filter      pgtype.Bool
}

type MetadataFieldsReference struct {
	WindowTypeID     int64
	MetadataFieldsID int64
}

type Processor struct {
	ID               int64
	Name             string
	Runtime          string
	ConnectionString string
	Created          pgtype.Timestamp
	ProjectName      pgtype.Text
}

type Result struct {
	ID           int64
	WindowsID    pgtype.Int8
	WindowTypeID pgtype.Int8
	AlgorithmID  pgtype.Int8
	ResultValue  pgtype.Float8
	ResultArray  []float64
	ResultJson   []byte
	State        AlgorithmState
	Error        []byte
}

type Task struct {
	Name             string
	AstHash          string
	WorkerName       string
	Description      string
	ExecutionTimeout pgtype.Int4
	Deadline         pgtype.Int4
	RetryCount       pgtype.Int4
	BackoffStrategy  NullBackoffStrategy
	InputModel       []byte
	OutputModel      []byte
	GitCommitHash    string
	IsActive         pgtype.Bool
	RegisteredAt     pgtype.Timestamptz
}

type TaskExecution struct {
	ID                       int32
	WorkflowRunid            int32
	TaskName                 string
	TaskAstHash              string
	TaskWorkerName           string
	RequestedAt              pgtype.Timestamptz
	Result                   []byte
	Failed                   pgtype.Bool
	CompletedAt              pgtype.Timestamptz
	ResultRecievedAt         pgtype.Timestamptz
	FailureSource            NullFailureSource
	FailureCategory          NullFailureCategory
	CpuSeconds               pgtype.Int4
	MemoryGibSeconds         pgtype.Int4
	ExecutionDurationSeconds pgtype.Int4
}

type TaskRequiredDataFunction struct {
	TaskName       string
	TaskAstHash    string
	TaskWorkerName string
	DfName         string
	DfAstHash      string
	DfWorkerName   string
}

type Window struct {
	ID           int64
	WindowTypeID int64
	TimeFrom     pgtype.Timestamp
	TimeTo       pgtype.Timestamp
	Origin       string
	Created      pgtype.Timestamp
	State        WindowState
}

type WindowType struct {
	ID          int64
	Name        string
	Version     string
	Description string
	Created     pgtype.Timestamp
}

type WindowTypeMetadataField struct {
	WindowTypeName           string
	WindowTypeVersion        string
	MetadataFieldID          int64
	MetadataFieldName        string
	MetadataFieldDescription string
}

type Worker struct {
	Name          string
	Md5Hash       string
	ConnectionUrl string
	IsServing     pgtype.Bool
}

type Workflow struct {
	ID                   int32
	Name                 string
	Hash                 string
	WorkerName           string
	Source               WorkflowSource
	Description          pgtype.Text
	InputModel           []byte
	TaskConcurrencyLimit pgtype.Int4
	HaltOnFailure        pgtype.Bool
	GitCommitHash        string
	IsActive             pgtype.Bool
	RegisteredAt         pgtype.Timestamptz
}

type WorkflowEdge struct {
	WorkflowID         int32
	FromTaskName       string
	FromTaskAstHash    string
	FromTaskWorkerName string
	ToTaskName         string
	ToTaskAstHash      string
	ToTaskWorkerName   string
}

type WorkflowTransistivePair struct {
	WorkflowID         int32
	FromTaskName       string
	FromTaskAstHash    string
	FromTaskWorkerName string
	ToTaskName         string
	ToTaskAstHash      string
	ToTaskWorkerName   string
}

type WorkflowTrigger struct {
	ID                  int32
	WorkflowID          int32
	CreatedAt           pgtype.Timestamptz
	Source              TriggerSource
	Status              TriggerStatus
	ExecutionParameters []byte
}
