// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeNonce = `-- name: ConsumeNonce :one
UPDATE
    worker_nonce
SET
    used = TRUE
WHERE
    nonce = $1
    AND worker_id = $2
    AND used = FALSE
    AND expires_at > now()
RETURNING
    id,
    worker_id
`

type ConsumeNonceParams struct {
	Nonce    []byte
	WorkerID pgtype.UUID
}

type ConsumeNonceRow struct {
	ID       pgtype.UUID
	WorkerID pgtype.UUID
}

func (q *Queries) ConsumeNonce(ctx context.Context, arg ConsumeNonceParams) (ConsumeNonceRow, error) {
	row := q.db.QueryRow(ctx, consumeNonce, arg.Nonce, arg.WorkerID)
	var i ConsumeNonceRow
	err := row.Scan(&i.ID, &i.WorkerID)
	return i, err
}

const createNonce = `-- name: CreateNonce :one
INSERT INTO worker_nonce (worker_id, nonce)
    VALUES ($1, $2)
RETURNING
    id, nonce, expires_at
`

type CreateNonceParams struct {
	WorkerID pgtype.UUID
	Nonce    []byte
}

type CreateNonceRow struct {
	ID        pgtype.UUID
	Nonce     []byte
	ExpiresAt pgtype.Timestamptz
}

// ============================================================
// Nonce
// ============================================================
func (q *Queries) CreateNonce(ctx context.Context, arg CreateNonceParams) (CreateNonceRow, error) {
	row := q.db.QueryRow(ctx, createNonce, arg.WorkerID, arg.Nonce)
	var i CreateNonceRow
	err := row.Scan(&i.ID, &i.Nonce, &i.ExpiresAt)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO worker_session (worker_id, access_key, expires_at)
    VALUES ($1, $2, $3)
RETURNING
    id, access_key, expires_at
`

type CreateSessionParams struct {
	WorkerID  pgtype.UUID
	AccessKey []byte
	ExpiresAt pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID        pgtype.UUID
	AccessKey []byte
	ExpiresAt pgtype.Timestamptz
}

// ============================================================
// Session
// ============================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.WorkerID, arg.AccessKey, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(&i.ID, &i.AccessKey, &i.ExpiresAt)
	return i, err
}

const deleteExpiredNonces = `-- name: DeleteExpiredNonces :exec
DELETE FROM worker_nonce
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredNonces(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNonces)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM worker_session
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
    id,
    worker_id,
    expires_at
FROM
    worker_session
WHERE
    access_key = $1
    AND revoked = FALSE
    AND expires_at > now()
`

type GetSessionRow struct {
	ID        pgtype.UUID
	WorkerID  pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSession(ctx context.Context, accessKey []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, accessKey)
	var i GetSessionRow
	err := row.Scan(&i.ID, &i.WorkerID, &i.ExpiresAt)
	return i, err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT
    id,
    public_key,
    connection_url,
    is_serving,
    created_at
FROM
    worker
WHERE
    id = $1
`

func (q *Queries) GetWorkerByID(ctx context.Context, id pgtype.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.ConnectionUrl,
		&i.IsServing,
		&i.CreatedAt,
	)
	return i, err
}

const registerWorker = `-- name: RegisterWorker :one
INSERT INTO worker (public_key, connection_url)
    VALUES ($1, $2)
RETURNING
    id
`

type RegisterWorkerParams struct {
	PublicKey     string
	ConnectionUrl string
}

// ============================================================
// Worker
// ============================================================
func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, registerWorker, arg.PublicKey, arg.ConnectionUrl)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE
    worker_session
SET
    revoked = TRUE
WHERE
    access_key = $1
`

func (q *Queries) RevokeSession(ctx context.Context, accessKey []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, accessKey)
	return err
}

const setWorkerServing = `-- name: SetWorkerServing :exec
UPDATE
    worker
SET
    is_serving = $1
WHERE
    id = $2
`

type SetWorkerServingParams struct {
	IsServing bool
	ID        pgtype.UUID
}

func (q *Queries) SetWorkerServing(ctx context.Context, arg SetWorkerServingParams) error {
	_, err := q.db.Exec(ctx, setWorkerServing, arg.IsServing, arg.ID)
	return err
}
