// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkWorkerExistsById = `-- name: CheckWorkerExistsById :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            worker
        WHERE
            id = $1)
`

func (q *Queries) CheckWorkerExistsById(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkerExistsById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const consumeNonce = `-- name: ConsumeNonce :one
UPDATE
    worker_nonce
SET
    used = TRUE
WHERE
    worker_id = $1
    AND id = $2
    AND used = FALSE
    AND expires_at > now()
RETURNING
    id,
    nonce,
    worker_id
`

type ConsumeNonceParams struct {
	WorkerID pgtype.UUID
	NonceID  pgtype.UUID
}

type ConsumeNonceRow struct {
	ID       pgtype.UUID
	Nonce    []byte
	WorkerID pgtype.UUID
}

func (q *Queries) ConsumeNonce(ctx context.Context, arg ConsumeNonceParams) (ConsumeNonceRow, error) {
	row := q.db.QueryRow(ctx, consumeNonce, arg.WorkerID, arg.NonceID)
	var i ConsumeNonceRow
	err := row.Scan(&i.ID, &i.Nonce, &i.WorkerID)
	return i, err
}

const createDataFunction = `-- name: CreateDataFunction :exec
INSERT INTO data_function (
    name,
    git_commit_hash,
    git_commit_hash,
    worker_id,
    output_model,
    status,
    input_model,
    execution_timeout_seconds,
    ttl_seconds)
VALUES (
    $1,
    $2,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8)
`

type CreateDataFunctionParams struct {
	Name                    string
	GitCommitHash           string
	WorkerID                pgtype.UUID
	OutputModel             []byte
	Status                  AssetStatus
	InputModel              []byte
	ExecutionTimeoutSeconds pgtype.Int4
	TtlSeconds              pgtype.Int4
}

// ============================================================
// Data Functions
// ============================================================
func (q *Queries) CreateDataFunction(ctx context.Context, arg CreateDataFunctionParams) error {
	_, err := q.db.Exec(ctx, createDataFunction,
		arg.Name,
		arg.GitCommitHash,
		arg.WorkerID,
		arg.OutputModel,
		arg.Status,
		arg.InputModel,
		arg.ExecutionTimeoutSeconds,
		arg.TtlSeconds,
	)
	return err
}

const createNonce = `-- name: CreateNonce :one
INSERT INTO worker_nonce (
    worker_id,
    nonce)
VALUES (
    $1,
    $2)
RETURNING
    id,
    nonce,
    expires_at
`

type CreateNonceParams struct {
	WorkerID pgtype.UUID
	Nonce    []byte
}

type CreateNonceRow struct {
	ID        pgtype.UUID
	Nonce     []byte
	ExpiresAt pgtype.Timestamptz
}

// ============================================================
// Nonce
// ============================================================
func (q *Queries) CreateNonce(ctx context.Context, arg CreateNonceParams) (CreateNonceRow, error) {
	row := q.db.QueryRow(ctx, createNonce, arg.WorkerID, arg.Nonce)
	var i CreateNonceRow
	err := row.Scan(&i.ID, &i.Nonce, &i.ExpiresAt)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO worker_session (
    worker_id,
    access_key,
    expires_at)
VALUES (
    $1,
    $2,
    $3)
RETURNING
    id,
    access_key,
    expires_at
`

type CreateSessionParams struct {
	WorkerID  pgtype.UUID
	AccessKey []byte
	ExpiresAt pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID        pgtype.UUID
	AccessKey []byte
	ExpiresAt pgtype.Timestamptz
}

// ============================================================
// Session
// ============================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.WorkerID, arg.AccessKey, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(&i.ID, &i.AccessKey, &i.ExpiresAt)
	return i, err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO task (
    name,
    git_commit_hash,
    worker_id,
    description,
    execution_timeout,
    deadline,
    retry_count,
    backoff_strategy,
    input_model,
    output_model,
    git_commit_hash,
    status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $2,
    $11)
`

type CreateTaskParams struct {
	Name             string
	GitCommitHash    string
	WorkerID         pgtype.UUID
	Description      string
	ExecutionTimeout pgtype.Int4
	Deadline         pgtype.Int4
	RetryCount       pgtype.Int4
	BackoffStrategy  NullBackoffStrategy
	InputModel       []byte
	OutputModel      []byte
	Status           AssetStatus
}

// ============================================================
// Task
// ============================================================
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.Name,
		arg.GitCommitHash,
		arg.WorkerID,
		arg.Description,
		arg.ExecutionTimeout,
		arg.Deadline,
		arg.RetryCount,
		arg.BackoffStrategy,
		arg.InputModel,
		arg.OutputModel,
		arg.Status,
	)
	return err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflow (
    name,
    hash,
    worker_id,
    source,
    description,
    input_model,
    task_concurrency_limit,
    halt_on_failure,
    git_commit_hash,
    status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10)
RETURNING
    id
`

type CreateWorkflowParams struct {
	Name                 string
	Hash                 string
	WorkerID             pgtype.UUID
	Source               WorkflowSource
	Description          pgtype.Text
	InputModel           []byte
	TaskConcurrencyLimit pgtype.Int4
	HaltOnFailure        pgtype.Bool
	GitCommitHash        string
	Status               AssetStatus
}

// ============================================================
// Workflows
// ============================================================
func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (int32, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.Name,
		arg.Hash,
		arg.WorkerID,
		arg.Source,
		arg.Description,
		arg.InputModel,
		arg.TaskConcurrencyLimit,
		arg.HaltOnFailure,
		arg.GitCommitHash,
		arg.Status,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createWorkflowEdge = `-- name: CreateWorkflowEdge :exec
INSERT INTO workflow_edge (
    workflow_id,
    from_task_name,
    from_task_git_commit_hash,
    from_task_worker_id,
    to_task_name,
    to_task_git_commit_hash,
    to_task_worker_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7)
ON CONFLICT
    DO NOTHING
`

type CreateWorkflowEdgeParams struct {
	WorkflowID            int32
	FromTaskName          string
	FromTaskGitCommitHash string
	FromTaskWorkerID      pgtype.UUID
	ToTaskName            string
	ToTaskGitCommitHash   string
	ToTaskWorkerID        pgtype.UUID
}

func (q *Queries) CreateWorkflowEdge(ctx context.Context, arg CreateWorkflowEdgeParams) error {
	_, err := q.db.Exec(ctx, createWorkflowEdge,
		arg.WorkflowID,
		arg.FromTaskName,
		arg.FromTaskGitCommitHash,
		arg.FromTaskWorkerID,
		arg.ToTaskName,
		arg.ToTaskGitCommitHash,
		arg.ToTaskWorkerID,
	)
	return err
}

const createWorkflowTransitivepair = `-- name: CreateWorkflowTransitivepair :exec
INSERT INTO workflow_transitive_pair (
    workflow_id,
    from_task_name,
    from_task_git_commit_hash,
    from_task_worker_id,
    to_task_name,
    to_task_git_commit_hash,
    to_task_worker_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7)
ON CONFLICT
    DO NOTHING
`

type CreateWorkflowTransitivepairParams struct {
	WorkflowID            int32
	FromTaskName          string
	FromTaskGitCommitHash string
	FromTaskWorkerID      pgtype.UUID
	ToTaskName            string
	ToTaskGitCommitHash   string
	ToTaskWorkerID        pgtype.UUID
}

func (q *Queries) CreateWorkflowTransitivepair(ctx context.Context, arg CreateWorkflowTransitivepairParams) error {
	_, err := q.db.Exec(ctx, createWorkflowTransitivepair,
		arg.WorkflowID,
		arg.FromTaskName,
		arg.FromTaskGitCommitHash,
		arg.FromTaskWorkerID,
		arg.ToTaskName,
		arg.ToTaskGitCommitHash,
		arg.ToTaskWorkerID,
	)
	return err
}

const deleteExpiredNonces = `-- name: DeleteExpiredNonces :exec
DELETE FROM worker_nonce
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredNonces(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNonces)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM worker_session
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
    id,
    worker_id,
    expires_at
FROM
    worker_session
WHERE
    access_key = $1
    AND revoked = FALSE
    AND expires_at > now()
`

type GetSessionRow struct {
	ID        pgtype.UUID
	WorkerID  pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSession(ctx context.Context, accessKey []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, accessKey)
	var i GetSessionRow
	err := row.Scan(&i.ID, &i.WorkerID, &i.ExpiresAt)
	return i, err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT
    id,
    public_key,
    connection_url,
    is_serving,
    created_at
FROM
    worker
WHERE
    id = $1
`

func (q *Queries) GetWorkerByID(ctx context.Context, id pgtype.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.ConnectionUrl,
		&i.IsServing,
		&i.CreatedAt,
	)
	return i, err
}

const registerWorker = `-- name: RegisterWorker :one
INSERT INTO worker (
    public_key,
    connection_url)
VALUES (
    $1,
    $2)
RETURNING
    id
`

type RegisterWorkerParams struct {
	PublicKey     []byte
	ConnectionUrl string
}

// ============================================================
// Worker
// ============================================================
func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, registerWorker, arg.PublicKey, arg.ConnectionUrl)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const requireDatafunctionForTask = `-- name: RequireDatafunctionForTask :exec
INSERT INTO task_required_data_function (
    task_name,
    task_git_commit_hash,
    task_worker_id,
    df_name,
    df_git_commit_hash,
    df_worker_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6)
`

type RequireDatafunctionForTaskParams struct {
	TaskName          string
	TaskGitCommitHash string
	TaskWorkerID      pgtype.UUID
	DfName            string
	DfGitCommitHash   string
	DfWorkerID        pgtype.UUID
}

func (q *Queries) RequireDatafunctionForTask(ctx context.Context, arg RequireDatafunctionForTaskParams) error {
	_, err := q.db.Exec(ctx, requireDatafunctionForTask,
		arg.TaskName,
		arg.TaskGitCommitHash,
		arg.TaskWorkerID,
		arg.DfName,
		arg.DfGitCommitHash,
		arg.DfWorkerID,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE
    worker_session
SET
    revoked = TRUE
WHERE
    access_key = $1
`

func (q *Queries) RevokeSession(ctx context.Context, accessKey []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, accessKey)
	return err
}

const setWorkerServing = `-- name: SetWorkerServing :exec
UPDATE
    worker
SET
    is_serving = $1
WHERE
    id = $2
`

type SetWorkerServingParams struct {
	IsServing bool
	ID        pgtype.UUID
}

func (q *Queries) SetWorkerServing(ctx context.Context, arg SetWorkerServingParams) error {
	_, err := q.db.Exec(ctx, setWorkerServing, arg.IsServing, arg.ID)
	return err
}
